! r4 - AS 65002 "ISP", dual-homed to r1 and r3, owns the 10.10.200.0/24 LAN
frr defaults traditional
hostname r4
log stdout
service integrated-vtysh-config
!
interface lo
 ip address 4.4.4.4/32
!
router bgp 65002
 bgp router-id 4.4.4.4
 no bgp ebgp-requires-policy
 neighbor 10.10.14.2 remote-as 65001
 neighbor 10.10.34.2 remote-as 65001
 !
 address-family ipv4 unicast
  network 10.10.200.0/24
 exit-address-family
!
line vty
!
