! r1 - AS 65001 edge router, eBGP to r4 (primary path, local-pref 200)
frr defaults traditional
hostname r1
log stdout
service integrated-vtysh-config
!
interface lo
 ip address 1.1.1.1/32
!
interface @IF[10.10.12.2]
 ip ospf network non-broadcast
!
interface @IF[10.10.13.2]
 ip ospf network non-broadcast
!
router ospf
 ospf router-id 1.1.1.1
 neighbor 10.10.12.3 priority 1 poll-interval 10
 neighbor 10.10.13.3 priority 1 poll-interval 10
 network 1.1.1.1/32 area 0
 network 10.10.12.0/24 area 0
 network 10.10.13.0/24 area 0
!
route-map FROM-R4 permit 10
 set local-preference 200
!
router bgp 65001
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 neighbor 10.10.14.3 remote-as 65002
 neighbor 2.2.2.2 remote-as 65001
 neighbor 2.2.2.2 update-source lo
 neighbor 3.3.3.3 remote-as 65001
 neighbor 3.3.3.3 update-source lo
 !
 address-family ipv4 unicast
  neighbor 10.10.14.3 route-map FROM-R4 in
  neighbor 2.2.2.2 next-hop-self
  neighbor 3.3.3.3 next-hop-self
 exit-address-family
!
line vty
!
