! r2 - AS 65001 core router, owns the 10.10.100.0/24 LAN
frr defaults traditional
hostname r2
log stdout
service integrated-vtysh-config
!
interface lo
 ip address 2.2.2.2/32
!
interface @IF[10.10.12.3]
 ip ospf network non-broadcast
!
interface @IF[10.10.23.2]
 ip ospf network non-broadcast
!
router ospf
 ospf router-id 2.2.2.2
 neighbor 10.10.12.2 priority 1 poll-interval 10
 neighbor 10.10.23.3 priority 1 poll-interval 10
 network 2.2.2.2/32 area 0
 network 10.10.12.0/24 area 0
 network 10.10.23.0/24 area 0
!
router bgp 65001
 bgp router-id 2.2.2.2
 neighbor 1.1.1.1 remote-as 65001
 neighbor 1.1.1.1 update-source lo
 neighbor 3.3.3.3 remote-as 65001
 neighbor 3.3.3.3 update-source lo
 !
 address-family ipv4 unicast
  network 10.10.100.0/24
 exit-address-family
!
line vty
!
